name: anis_survival_ai
description: ANIS SURVIVAL AI - Offline survival app
publish_to: 'none'
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  geolocator: ^9.0.2
  sqflite: ^2.2.5
  path_provider: ^2.0.14
  battery_plus: ^4.0.3
  speech_to_text: ^6.0.0
  flutter_tts: ^3.5.0
  audioplayers: ^1.1.0
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
